#
# obsidian-plugin-e2e-test | CSpell config
#
version: '0.2'
ignorePaths:
  - test-results/
  - playwright-report/
  - dist/
  - node_modules/
dictionaryDefinitions:
  - name: cspell-obsidian-e2e
    path: ./.vscode/cspell-obsidian-e2e.txt
    addWords: true
caseSensitive: false
dictionaries:
  - cspell-obsidian-e2e
words: []
ignoreWords: []
import: []
