# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build

  install:
    deps: []
    cmds:
      - yarn install

  build:
    deps: [install]
    cmds:
      - yarn build
      - yarn test

  run:
    deps: [build, install-obsidian]
    cmds:
      - cmd: xvfb-run --auto-servernum yarn test
    env:
      DISPLAY: ":99"
      OBSIDIAN_PATH: "./.build/obsidian/obsidian"

  install-obsidian:
    cmds:
      - cmd: bash ./build/install-obsidian.sh
        platforms: [linux]
      - cmd: echo "Done."

  install-proto:
    cmds:
      - cmd: sh ./build/install-proto.sh
        platforms: [linux]
      - cmd: echo "Done."

  docker-build:
    cmds:
      - cmd: docker build -t obsidian .

  docker-run:
    cmds:
      - cmd: docker run --rm --security-opt seccomp="$(current_dir)/chrome.json" obsidian
