name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  e2e_tests:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: sudo npm install -g corepack@latest
      - run: yarn install
      - run: yarn build

      # #todo #jovaneen Disable tests until we migrate away from Spectron to something like WebdriverIO
      # - name: Run tests
      #   run: make e2e
