name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  e2e_tests:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: sudo npm install -g corepack@latest

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ github.token }}

      # This will install a local Obsidian for testing and install 'proto'
      - run: task setup

      - run: yarn install
      - run: yarn build

      - run: |
          export DISPLAY=":99"
          export OBSIDIAN_PATH=./.build/obsidian/obsidian
          xvfb-run yarn test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
